# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request]

# Set the build type here
env:
  CI_ENV_BUILD_TYPE: Debug
  B_BUILD_DIR: build
  B_BUILD_TYPE: Debug
  INPUTLEAP_VERSION_STAGE: Debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linux-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu:18.04", "ubuntu:20.04"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Update image and install pre-reqs
        run: |
          apt-get update -y
          # needed for add-apt-repository
          apt-get install -y software-properties-common
          # actions/checkout@v3 wants newer git than what's in default repositories
          add-apt-repository ppa:git-core/ppa
          apt-get update -y
          apt-get dist-upgrade -y
          apt-get install -y git g++ libxtst-dev libxinerama-dev libxrandr-dev libice-dev libsm-dev qtdeclarative5-dev libavahi-compat-libdnssd-dev libcurl4-openssl-dev libssl-dev cmake ninja-build

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Work around git safe directory check
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Run the build
        run: sh -x ./clean_build.sh
        env:
            VERBOSE: 1

      - name: Run the tests
        run: |
            cd ${B_BUILD_DIR}
            ctest --verbose
